# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'
      - 'img/**'

jobs:
  converttopdf:
    name: Markdown to PDF and HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: ./
          output_dir: pdfs
          images_dir: img
          # for example <img src="./images/file-name.png">
          image_import: ./img
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: pm
          path: pdfs
