# .github/workflows/convert-to-pdf.yml

name: Markdown to PDF and HTML
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'pms/**.md'
      - 'pms/images/**'
      - 'sonstige/**.md'
      - 'images/**'
  release:
    types: [published]

jobs:
  topdf-with-image:
    name: Markdown to PDF mit Bild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v3
        with:
          input_dir: pms
          output_dir: pdfs-mit-bild
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: pms-img
          path: pdfs-mit-bild

  sonstige-topdf-with-image:
    name: Sonstige Markdown to PDF mit Bild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v3
        with:
          input_dir: sonstige
          output_dir: pdfs-mit-bild
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: /images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: pms-img
          path: pdfs-mit-bild
