# .github/workflows/convert-to-pdf.yml

name: Markdown to PDF and HTML
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'pms/**.md'
      - 'pms/images/**'
  release:
    types: [published]

jobs:
  converttopdf:
    name: Markdown to PDF mit Bild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: pms
          images_dir: ./pms/images
          output_dir: pdfs-mit-bild
          # for example <img src="./images/file-name.png">
          image_import: images
          # Default is true, can set to false to only get PDF files
          build_html: false
          build_pdf: true
      - uses: actions/upload-artifact@v1
        with:
          name: pms
          path: pdfs-mit-bild

    name: Markdown to PDF ohne Bilder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: pms
          output_dir: pdfs-ohne-bild
          # Default is true, can set to false to only get PDF files
          build_html: false
          build_pdf: true
      - uses: actions/upload-artifact@v1
        with:
          name: pms
          path: pdfs-ohne-bild

